---
default_language_version:
  python: python3
minimum_pre_commit_version: "1.14.0"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: check-yaml
    files: .*\.(yaml|yml)$
    # https://github.com/pre-commit/pre-commit-hooks/issues/273
    args: ["--unsafe"]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3
    types_or: [file]
    files: scan_ble
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-black
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-black
    types: [file]
    files: scan_ble
- repo: https://github.com/codespell-project/codespell.git
  rev: v2.2.2
  hooks:
  - id: codespell
    name: codespell
    description: Checks for common misspellings in text files.
    entry: codespell
    language: python
    types: [text]
    args: []
    require_serial: false
    additional_dependencies: []
